"""weekly instrument rosters for point in time stock pools

Revision ID: 2810aefa1b70
Revises: 6fca8b9578af
Create Date: 2026-08-18 23:41:17.282009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2810aefa1b70'
down_revision: Union[str, None] = '6fca8b9578af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_snapshots', sa.Column('master_publish_sequence', sa.BigInteger(), nullable=True))
    op.add_column('instrument_master_snapshot_members', sa.Column('product_category', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument_master_snapshot_members', 'product_category')
    op.drop_column('data_snapshots', 'master_publish_sequence')
    # ### end Alembic commands ###
