"""add jquants market data sync

Revision ID: abffefb9fa61
Revises: 474737d65838
Create Date: 2026-08-15 01:53:38.440003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'abffefb9fa61'
down_revision: Union[str, None] = '474737d65838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_code', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id'),
    sa.UniqueConstraint('source', 'source_code', name='uq_instrument_source_code')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.Enum('initial', 'incremental', 'full_reconcile', name='sync_mode'), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'no_change', 'partial_failed', 'failed', 'cancelled', name='sync_run_status'), nullable=False),
    sa.Column('current_endpoint', sa.String(length=100), nullable=True),
    sa.Column('target_dates', sa.Integer(), nullable=False),
    sa.Column('processed_dates', sa.Integer(), nullable=False),
    sa.Column('pages_received', sa.Integer(), nullable=False),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_new', sa.Integer(), nullable=False),
    sa.Column('rows_unchanged', sa.Integer(), nullable=False),
    sa.Column('rows_changed', sa.Integer(), nullable=False),
    sa.Column('requested_start', sa.Date(), nullable=True),
    sa.Column('requested_end', sa.Date(), nullable=True),
    sa.Column('actual_min', sa.Date(), nullable=True),
    sa.Column('actual_max', sa.Date(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('endpoint_publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('staging', 'published', 'failed', 'cancelled', name='publication_status'), nullable=False),
    sa.Column('api_version', sa.String(length=20), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_run_id', 'endpoint', name='uq_publication_run_endpoint')
    )
    op.create_index(op.f('ix_endpoint_publications_sync_run_id'), 'endpoint_publications', ['sync_run_id'], unique=False)
    op.create_table('sync_target_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('source_calendar_code', sa.String(length=20), nullable=False),
    sa.Column('fetch_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_run_id', 'trade_date', name='uq_sync_target_date')
    )
    op.create_index(op.f('ix_sync_target_dates_sync_run_id'), 'sync_target_dates', ['sync_run_id'], unique=False)
    op.create_table('bar_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('raw_open', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_high', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_low', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_close', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('trading_value', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('adjusted_open', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('adjusted_high', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('adjusted_low', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('adjusted_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('adjustment_factor', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['endpoint_publications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'instrument_id', 'trade_date', 'session', 'content_hash', name='uq_bar_version_content')
    )
    op.create_index(op.f('ix_bar_versions_instrument_id'), 'bar_versions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_bar_versions_is_current'), 'bar_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_bar_versions_publication_id'), 'bar_versions', ['publication_id'], unique=False)
    op.create_index(op.f('ix_bar_versions_trade_date'), 'bar_versions', ['trade_date'], unique=False)
    op.create_table('instrument_master_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['endpoint_publications.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'as_of_date', 'sync_run_id', name='uq_master_snapshot')
    )
    op.create_index(op.f('ix_instrument_master_snapshots_sync_run_id'), 'instrument_master_snapshots', ['sync_run_id'], unique=False)
    op.create_table('raw_source_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['endpoint_publications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'page_index', name='uq_raw_page')
    )
    op.create_index(op.f('ix_raw_source_pages_expires_at'), 'raw_source_pages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_raw_source_pages_publication_id'), 'raw_source_pages', ['publication_id'], unique=False)
    op.create_table('instrument_master_snapshot_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('company_name_en', sa.String(length=300), nullable=True),
    sa.Column('market_code', sa.String(length=20), nullable=False),
    sa.Column('market_name', sa.String(length=100), nullable=True),
    sa.Column('sector_17', sa.String(length=20), nullable=True),
    sa.Column('sector_33', sa.String(length=20), nullable=True),
    sa.Column('scale_category', sa.String(length=100), nullable=True),
    sa.Column('inferred_security_class', sa.String(length=50), nullable=False),
    sa.Column('classification_method', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['instrument_master_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'instrument_id', name='uq_snapshot_instrument')
    )
    op.create_index(op.f('ix_instrument_master_snapshot_members_instrument_id'), 'instrument_master_snapshot_members', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_instrument_master_snapshot_members_snapshot_id'), 'instrument_master_snapshot_members', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_master_snapshot_members_snapshot_id'), table_name='instrument_master_snapshot_members')
    op.drop_index(op.f('ix_instrument_master_snapshot_members_instrument_id'), table_name='instrument_master_snapshot_members')
    op.drop_table('instrument_master_snapshot_members')
    op.drop_index(op.f('ix_raw_source_pages_publication_id'), table_name='raw_source_pages')
    op.drop_index(op.f('ix_raw_source_pages_expires_at'), table_name='raw_source_pages')
    op.drop_table('raw_source_pages')
    op.drop_index(op.f('ix_instrument_master_snapshots_sync_run_id'), table_name='instrument_master_snapshots')
    op.drop_table('instrument_master_snapshots')
    op.drop_index(op.f('ix_bar_versions_trade_date'), table_name='bar_versions')
    op.drop_index(op.f('ix_bar_versions_publication_id'), table_name='bar_versions')
    op.drop_index(op.f('ix_bar_versions_is_current'), table_name='bar_versions')
    op.drop_index(op.f('ix_bar_versions_instrument_id'), table_name='bar_versions')
    op.drop_table('bar_versions')
    op.drop_index(op.f('ix_sync_target_dates_sync_run_id'), table_name='sync_target_dates')
    op.drop_table('sync_target_dates')
    op.drop_index(op.f('ix_endpoint_publications_sync_run_id'), table_name='endpoint_publications')
    op.drop_table('endpoint_publications')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('instruments')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for native PostgreSQL enums. Keep
    # downgrade/re-upgrade repeatable for this migration chain.
    sa.Enum(name='publication_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sync_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sync_mode').drop(op.get_bind(), checkfirst=True)
